name: authenticator_app
description: Secure, polished authenticator app.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.6
  mobile_scanner: ^5.1.1
  totp: ^0.1.0
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.2.0
  crypto: ^3.0.3
  meta: ^1.16.0
  equatable: ^2.0.5

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
